[project]
name = "Refractometro"
version = "0.1.0"
description = "Aplicación gráfica para control de un refractometro"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dearpygui>=2.3.1",
    "pyserial>=3.5",
    "zaber-motion>=10.0.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pyinstaller>=6.22.0",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
