from __future__ import annotations

from typing import Protocol


class Motor(Protocol):
    def connect(self, port: str) -> None: ...

    def disconnect(self) -> None: ...

    def move_absolute(self, position_mm: float) -> None: ...

    def stop(self) -> None: ...


class Sensor(Protocol):
    def connect(self, port: str, baud_rate: int) -> None: ...

    def disconnect(self) -> None: ...

    def read_voltage(self) -> float: ...
